---
title: "Lab 5"
author: ""
date: "Due on 04/17 at 11:59 PM"
output: pdf_document
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Collaborators: Abhiram Bobba (akbobba2), Arnav Kethana (kethana2), Kavin Mohan (kavinm2), Shyam Peden (speden2), Rohan Nadkarni (rohansn2)

```{r, message=FALSE, warning=FALSE}
library(Lahman)
library(tidyverse)
library(retrosheet)
library(dplyr)
library(tidyr)
library(reshape2)
library(baseballr)
library(knitr)
library(shiny)
library(DT)
```


```{r, warning=FALSE, messafe=FALSE}
## load in dataset
raw_pitchers <- read_csv("raw_pitcher_fangraphs_2024.csv")

head(raw_pitchers)
```
```{r}
positions <- c(
  "1B" = 3,
  "2B" = 4,
  "3B" = 5,
  "SS" = 6,
  "LF" = 7,
  "CF" = 8,
  "RF" = 9,
  "OF" = "of",
  "IF" = "if"
)

oaa_by_team_position_2025 <- bind_rows(
  lapply(names(positions), function(pos_name) {
    statcast_leaderboards(
      leaderboard = "outs_above_average",
      year = 2025,
      fielding_type = "team",
      oaa_position = positions[[pos_name]],
      min_field = 0
    ) %>%
      mutate(position_group = pos_name)
  })
)

head(oaa_by_team_position_2025)
```

```{r}

oaa_summary <- oaa_by_team_position_2025 %>%
  mutate(
    side_group = case_when(
      position_group %in% c("3B", "SS") ~ "left_side",
      position_group %in% c("1B", "2B") ~ "right_side",
      position_group %in% c("LF", "CF", "RF") ~ "outfield",
      TRUE ~ NA_character_
    )
  ) %>%
  group_by(display_team_name) %>%
  summarise(
    
    # individual positions
    oaa_1B = sum(outs_above_average[position_group == "1B"], na.rm = TRUE),
    oaa_2B = sum(outs_above_average[position_group == "2B"], na.rm = TRUE),
    oaa_3B = sum(outs_above_average[position_group == "3B"], na.rm = TRUE),
    oaa_SS = sum(outs_above_average[position_group == "SS"], na.rm = TRUE),
    oaa_LF = sum(outs_above_average[position_group == "LF"], na.rm = TRUE),
    oaa_CF = sum(outs_above_average[position_group == "CF"], na.rm = TRUE),
    oaa_RF = sum(outs_above_average[position_group == "RF"], na.rm = TRUE),

    # grouped sides
    left_side_oaa = sum(
      outs_above_average[side_group == "left_side"],
      na.rm = TRUE
    ),

    right_side_oaa = sum(
      outs_above_average[side_group == "right_side"],
      na.rm = TRUE
    ),
    
    infield_oaa = sum(
      outs_above_average[position_group %in% c("1B", "2B", "3B", "SS")],
      na.rm = TRUE
    ),

    outfield_oaa = sum(
      outs_above_average[side_group == "outfield"],
      na.rm = TRUE
    ),

    total_oaa = sum(outs_above_average, na.rm = TRUE),

    .groups = "drop"
  )

head(oaa_summary)
```
```{r}
## save park factors 2024-2026 in a vector
park_factors <- c(
  "Rockies" = 112,
  "Athletics" = 109,
  "Twins" = 104,
  "D-backs" = 104,
  "Orioles" = 103,
  "Reds" = 103,
  "Phillies" = 102,
  "Dodgers" = 102,
  "Red Sox" = 102,
  "Yankees" = 102,
  "Nationals" = 101,
  "Astros" = 101,
  "Blue Jays" = 101,
  "Tigers" = 101,
  "Marlins" = 100,
  "Pirates" = 100,
  "Angels" = 100,
  "Royals" = 100,
  "Braves" = 100,
  "Mets" = 99,
  "Cardinals" = 98,
  "Guardians" = 98,
  "White Sox" = 98,
  "Giants" = 98,
  "Brewers" = 97,
  "Padres" = 97,
  "Cubs" = 95,
  "Rays" = 95,
  "Mariners" = 92,
  "Rangers" = 91
)
```

```{r}
team_lookup <- tibble(
  team_name = c(
    "ARI","ATL","BAL","BOS","CHC","CHW","CIN","CLE","COL","DET",
    "HOU","KCR","LAA","LAD","MIA","MIL","MIN","NYM","NYY","ATH",
    "PHI","PIT","SDP","SEA","SFG","STL","TBR","TEX","TOR","WSN"
  ),
  display_team_name = c(
    "D-backs","Braves","Orioles","Red Sox","Cubs","White Sox",
    "Reds","Guardians","Rockies","Tigers","Astros","Royals",
    "Angels","Dodgers","Marlins","Brewers","Twins","Mets",
    "Yankees","Athletics","Phillies","Pirates","Padres","Mariners",
    "Giants","Cardinals","Rays","Rangers","Blue Jays","Nationals"
  )
)

park_factors_df <- enframe(
  park_factors,
  name = "display_team_name",
  value = "park_factor"
)

park_factors_df <- enframe(
  park_factors,
  name = "display_team_name",
  value = "park_factor"
)

model_data <- raw_pitchers %>%
  left_join(team_lookup, by = "team_name") %>%
  left_join(oaa_summary, by = "display_team_name") %>%
  left_join(park_factors_df, by = "display_team_name")
head(model_data)
```
```{r}
write.csv(model_data, "model_data.csv", row.names = FALSE)
```

```{r}
## split data into train test
set.seed(42)

model_df <- model_data %>%
  select(
    PlayerName,
    BABIP,
    K_pct,
    BB_pct,
    GB_pct,
    FB_pct,
    LD_pct,
    Pull_pct,
    Hard_pct,
    left_side_oaa,
    right_side_oaa,
    infield_oaa,
    outfield_oaa,
    park_factor
  ) %>%
  na.omit()

train_idx <- sample(seq_len(nrow(model_df)), size = 0.8 * nrow(model_df))

train <- model_df[train_idx, ]
test  <- model_df[-train_idx, ]
head(train)
```

```{r}
## run glm 
babip_model <- glm(
  BABIP ~
    K_pct +
    BB_pct +
    GB_pct +
    LD_pct +
    Hard_pct +
    left_side_oaa +
    right_side_oaa +
    outfield_oaa +
    park_factor,
  data = train,
  family = gaussian()
)

summary(babip_model)

test$predicted_babip <- predict(babip_model, newdata = test)

rmse <- sqrt(mean((test$BABIP - test$predicted_babip)^2))
mae <- mean(abs(test$BABIP - test$predicted_babip))

rmse
mae
```
```{r}

## test with Logan Webb
pitcher_name <- "Logan Webb"
new_team <- "Guardians"
new_park <- "Rockies"

pitcher_row <- model_data %>%
  filter(PlayerName == pitcher_name) %>%
  slice(1)

def_row <- oaa_summary %>%
  filter(display_team_name == new_team)

park_row <- park_factors_df %>%
  filter(display_team_name == new_park)

cf_row <- pitcher_row %>%
  mutate(
    left_side_oaa = def_row$left_side_oaa,
    right_side_oaa = def_row$right_side_oaa,
    outfield_oaa = def_row$outfield_oaa,
    park_factor = park_row$park_factor
  )

current_babip <- predict(babip_model, newdata = pitcher_row)

counterfactual_babip <- predict(
  babip_model,
  newdata = cf_row
)

current_babip
counterfactual_babip

counterfactual_babip - current_babip
```
```{r}
## ranks BABIP out of all possible ballpark/defense combos 
rank_counterfactuals <- function(pitcher_name) {
  
  pitcher_row <- model_data %>%
    filter(PlayerName == pitcher_name) %>%
    slice(1)
  
  current_team <- pitcher_row$display_team_name[1]
  
  current_pred <- predict(
    babip_model,
    newdata = pitcher_row
  )[1]
  
  defense_options <- oaa_summary %>%
    filter(display_team_name != current_team) %>%
    select(
      defense_team = display_team_name,
      left_side_oaa,
      right_side_oaa,
      outfield_oaa
    )
  
  park_options <- park_factors_df %>%
    filter(display_team_name != current_team) %>%
    rename(
      park_team = display_team_name
    )
  
  cf_grid <- crossing(
    defense_options,
    park_options
  )
  
  cf_preds <- cf_grid %>%
    mutate(
      PlayerName = pitcher_name,
      K_pct = pitcher_row$K_pct,
      BB_pct = pitcher_row$BB_pct,
      GB_pct = pitcher_row$GB_pct,
      LD_pct = pitcher_row$LD_pct,
      Hard_pct = pitcher_row$Hard_pct
    ) %>%
    mutate(
      predicted_babip = round(
        predict(babip_model, newdata = .),
        3
      ),
      
      current_team = current_team,
      
      current_babip = round(current_pred, 3),
      
      babip_diff = round(
        predicted_babip - current_babip,
        3
      )
    ) %>%
    arrange(predicted_babip) %>%
    mutate(
      rank = row_number(),
      
      current_rank = rank(
        c(predicted_babip, current_babip),
        ties.method = "first"
      )[length(predicted_babip) + 1],
      
      babip_diff_label = ifelse(
        babip_diff >= 0,
        paste0("+", sprintf("%.3f", babip_diff)),
        sprintf("%.3f", babip_diff)
      )
    ) %>%
    select(
      rank,
      current_babip,
      defense_team,
      park_team,
      predicted_babip,
      babip_diff_label
    )
  
  cf_preds
}
```

```{r}
## compares BABIP to original player situation
compare_counterfactual <- function(
  pitcher_name,
  new_defense_team,
  new_park_team
) {
  
  pitcher_row <- model_data %>%
    filter(PlayerName == pitcher_name) %>%
    slice(1)
  
  current_pred <- predict(
    babip_model,
    newdata = pitcher_row
  )[1]
  
  defense_row <- oaa_summary %>%
    filter(display_team_name == new_defense_team)
  
  park_row <- park_factors_df %>%
    filter(display_team_name == new_park_team)
  
  cf_row <- pitcher_row %>%
    mutate(
      left_side_oaa = defense_row$left_side_oaa,
      right_side_oaa = defense_row$right_side_oaa,
      outfield_oaa = defense_row$outfield_oaa,
      park_factor = park_row$park_factor
    )
  
  new_pred <- predict(
    babip_model,
    newdata = cf_row
  )[1]
  
  diff <- new_pred - current_pred
  
  tibble(
    pitcher = pitcher_name,
    
    current_team = pitcher_row$display_team_name[1],
    
    current_babip = sprintf("%.3f", current_pred),
    
    new_defense_team = new_defense_team,
    
    new_park_team = new_park_team,
    
    new_babip = sprintf("%.3f", new_pred),
    
    babip_diff = ifelse(
      diff >= 0,
      paste0("+", sprintf("%.3f", diff)),
      sprintf("%.3f", diff)
    ),
    
    interpretation = ifelse(
      diff < 0,
      "Lower BABIP allowed",
      "Higher BABIP allowed"
    )
  )
}
```

```{r}
## test with Logan Webb 
webb_results <- rank_counterfactuals("Logan Webb")
webb_results %>% head(10)

compare_counterfactual(
  pitcher_name = "Logan Webb",
  new_defense_team = "Cubs",
  new_park_team = "Mariners"
)
```



```{r}
ui <- fluidPage(
  p("Hello! Please enter a pitcher's name, new defense/team, and ballpark. The app compares the pitcher's current predicted situation to the selected defense and park, then shows the top 10 predicted BABIP environments."),

  textInput("pitcher", "Pitcher Name"),
  selectInput("team", "New Defense / Team", choices = teams),
  selectInput("park", "New Ballpark / Park", choices = sort(unique(park_factors_df$display_team_name))),

  actionButton("submit", "Run Simulation"),
  br(), br(),

  h4("Selected Counterfactual"),
  tableOutput("stats"),

  br(),

  h4("Top 10 Counterfactual Situations"),
  tableOutput("top10")
)

server <- function(input, output) {

  selected_result <- eventReactive(input$submit, {
    compare_counterfactual(
      pitcher_name = input$pitcher,
      new_defense_team = input$team,
      new_park_team = input$park
    )
  })

  top10_result <- eventReactive(input$submit, {
    rank_counterfactuals(input$pitcher) %>%
      arrange(predicted_babip) %>%
      head(10)
  })

  output$stats <- renderTable({
    selected_result()
  })

  output$top10 <- renderTable({
    top10_result()
  },
  digits = 3)
}
```


```{r}
shinyApp(ui = ui, server = server)
```

